- name: SQolytes
  github: Qambium/SQolytes
  link : https://qambium.fr/SQolytes
  description : >-
    Plateforme de visualisation de l'évolution d'Ips Typographus...
  more : '/programmation/2018-12-01-woodstock-js.html'

- name: Woodstock.js
  github: Qambium/Woodstock.js
  link : https://qambium.github.io/Woodstock.js
  description : >-
    Woodstock.js est une application open source
    permettant de cuber des arbres sur pied.
    Elle utilise la librairie javascript Quercus.js.
  more : '/programmation/2018-12-01-woodstock-js.html'

- name: Quercus.js
  github: Qambium/Quercus.js
  description : >-
    Quercus.js est une librairie javascript permettant
    de cuber des arbres sur pied en utilisant des tariffs
    de cubage.
  more : '/programmation/2018-12-01-quercus-js.html'
